# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: resources/icons/.*\.svg
    -   id: trailing-whitespace
        exclude: resources/icons/.*\.svg
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        exclude: resources/icons/.*\.svg
